const EFFECT_TEXT_MAP: Record<string, string> = {
  // Categories
  color: '色彩',
  blur: '模糊',
  distort: '变形',
  stylize: '风格化',
  keying: '抠像',

  // Effect names
  Brightness: '亮度',
  Contrast: '对比度',
  Exposure: '曝光',
  'Hue Shift': '色相偏移',
  Invert: '反相',
  Levels: '色阶',
  Saturation: '饱和度',
  Temperature: '色温',
  Grayscale: '灰度',
  Sepia: '褐色',
  Curves: '曲线',
  'Color Wheels': '色轮',
  Vibrance: '自然饱和度',
  'Gaussian Blur': '高斯模糊',
  'Box Blur': '方框模糊',
  'Motion Blur': '运动模糊',
  'Radial Blur': '径向模糊',
  'Zoom Blur': '缩放模糊',
  Pixelate: '像素化',
  'RGB Split': 'RGB 分离',
  Twirl: '旋涡',
  Wave: '波浪',
  'Bulge/Pinch': '膨胀/收缩',
  Kaleidoscope: '万花筒',
  Mirror: '镜像',
  'Fluted Glass': '条纹玻璃',
  Vignette: '暗角',
  'Film Grain': '胶片颗粒',
  Sharpen: '锐化',
  Posterize: '色调分离',
  Glow: '辉光',
  'Edge Detect': '边缘检测',
  Scanlines: '扫描线',
  'Color Glitch': '彩色故障',
  Halftone: '半色调',
  Dither: '抖动',
  ASCII: 'ASCII',
  Threshold: '阈值',
  'Chroma Key': '色度抠像',

  // Presets
  Vintage: '复古',
  Noir: '黑白',
  Cold: '冷调',
  Warm: '暖调',
  Dramatic: '戏剧',
  Faded: '褪色',

  // Common labels/options
  Amount: '强度',
  Size: '大小',
  Softness: '柔和度',
  Roundness: '圆度',
  Speed: '速度',
  Radius: '半径',
  Rings: '环数',
  'Samples/Ring': '每环采样',
  Strength: '强度',
  Density: '密度',
  Opacity: '不透明度',
  'Scroll Speed': '滚动速度',
  Intensity: '强度',
  'Front Color': '前景色',
  'Back Color': '背景色',
  'Original Colors': '保留原色',
  Inverted: '反转',
  Grid: '网格',
  Hex: '六边形',
  Square: '方形',
  Type: '类型',
  Classic: '经典',
  Gooey: '流体',
  Holes: '孔洞',
  Soft: '柔和',
  'Grain Mixer': '颗粒混合',
  'Grain Overlay': '颗粒叠加',
  'Grain Size': '颗粒大小',
  Pattern: '图案',
  Lines: '线条',
  Crosses: '十字',
  Dots: '点阵',
  Scales: '鳞片',
  Mode: '模式',
  Image: '图像',
  Linear: '线性',
  Radial: '径向',
  Style: '样式',
  Scaled: '缩放',
  Shape: '形状',
  Circle: '圆形',
  Diamond: '菱形',
  Palette: '调色板',
  'B&W': '黑白',
  'Game Boy': 'Game Boy',
  CGA: 'CGA',
  'Cell Size': '单元大小',
  Angle: '角度',
  Scale: '缩放',
  'Offset X': 'X 偏移',
  'Offset Y': 'Y 偏移',
  'Character Set': '字符集',
  Standard: '标准',
  Simple: '简洁',
  Blocks: '方块',
  Minimal: '极简',
  'Font Size': '字体大小',
  'Letter Spacing': '字距',
  'Line Height': '行高',
  'Match Source Color': '匹配原始颜色',
  'Text Color': '文字颜色',
  Background: '背景',
  'ASCII Opacity': 'ASCII 不透明度',
  'Original Opacity': '原图不透明度',
  Level: '级别',
  'Key Color': '抠像颜色',
  'Green Screen': '绿幕',
  'Blue Screen': '蓝幕',
  Tolerance: '容差',
  'Edge Softness': '边缘柔化',
  'Spill Suppression': '溢色抑制',
  Samples: '采样数',
  'Exposure (EV)': '曝光 (EV)',
  Offset: '偏移',
  Gamma: '伽马',
  Shift: '偏移',
  'Input Black': '输入黑场',
  'Input White': '输入白场',
  'Output Black': '输出黑场',
  'Output White': '输出白场',
  Tint: '色调',
  Shadows: '阴影',
  Midtones: '中间调',
  Highlights: '高光',
  Red: '红色',
  Green: '绿色',
  Blue: '蓝色',
  'Shadows Hue': '阴影色相',
  'Shadows Amount': '阴影强度',
  'Midtones Hue': '中间调色相',
  'Midtones Amount': '中间调强度',
  'Highlights Hue': '高光色相',
  'Highlights Amount': '高光强度',
  'Pixel Size': '像素大小',
  'Center X': '中心 X',
  'Center Y': '中心 Y',
  'Horizontal Amp': '水平振幅',
  'Vertical Amp': '垂直振幅',
  'Horizontal Freq': '水平频率',
  'Vertical Freq': '垂直频率',
  Segments: '分段数',
  Rotation: '旋转',
  Horizontal: '水平',
  Vertical: '垂直',
  'Shadow Color': '阴影颜色',
  'Highlight Color': '高光颜色',
  'Irregular Lines': '不规则线',
  'Distortion Shape': '畸变形状',
  Prism: '棱镜',
  Lens: '透镜',
  Contour: '轮廓',
  Cascade: '级联',
  Flat: '平面',
  Distortion: '畸变',
  Stretch: '拉伸',
  Blur: '模糊',
  Edges: '边缘',
  Margin: '边距',
  'Left Margin': '左边距',
  'Right Margin': '右边距',
  'Top Margin': '上边距',
  'Bottom Margin': '下边距',
  Bayer: '拜耳',
};

export function tEffectText(value: string): string {
  return EFFECT_TEXT_MAP[value] ?? value;
}

export function tEffectCategory(category: string): string {
  return EFFECT_TEXT_MAP[category] ?? category;
}
