export { embeddingsProvider, EMBEDDING_MODEL_ID, EMBEDDING_MODEL_DIM } from './embeddings-provider'
export { clipProvider, CLIP_MODEL_ID, CLIP_EMBEDDING_DIM } from './clip-provider'
export { buildEmbeddingText } from './context'
export { extractDominantColors } from './dominant-colors'
export type { PaletteEntry } from './dominant-colors'
export { deltaE2000 } from './lab-color'
export type { LabColor } from './lab-color'
