/**
 * Dopesheet row and group-header prop bundles.
 * Both the sheet rows and the property column render the same row content and
 * the same group headers, so both come from one bundle each. The bundles are
 * memoized on their individual values, never on an options object identity:
 * the row content and the group header are memoized components, and a fresh
 * bundle per render would re-render every visible row on every frame change.
 */

import { useMemo } from 'react'
import type {
  DopesheetGroupHeaderProps,
  DopesheetPropertyRowContentProps,
} from './dopesheet-row-renderers'

export interface UseDopesheetRowPropsOptions
  extends Omit<DopesheetPropertyRowContentProps, 'row' | 'options'> {
  expandedGroups: DopesheetGroupHeaderProps['expandedGroups']
  dimensionSeparationByProperty: DopesheetGroupHeaderProps['dimensionSeparationByProperty']
  setAllGroupsExpanded: DopesheetGroupHeaderProps['setAllGroupsExpanded']
  setGroupLocked: DopesheetGroupHeaderProps['setGroupLocked']
  toggleGroup: DopesheetGroupHeaderProps['toggleGroup']
  toggleGroupCurves: DopesheetGroupHeaderProps['toggleGroupCurves']
  handleClearGroup: DopesheetGroupHeaderProps['handleClearGroup']
}

export interface UseDopesheetRowPropsReturn {
  rowContentProps: Omit<DopesheetPropertyRowContentProps, 'row' | 'options'>
  groupHeaderProps: Omit<DopesheetGroupHeaderProps, 'group'>
}

/** Builds the memoized row-content and group-header bundles. */
export function useDopesheetRowProps(
  options: UseDopesheetRowPropsOptions,
): UseDopesheetRowPropsReturn {
  const {
  activateProperty, axisConstraintByProperty, autoKeyEnabledByProperty,
  beginPropertyLink, canClearRow, compoundPropertyRows,
  compoundSecondaryProperties, itemId, itemFrom,
  currentFrame, fps, disabled,
  expressionEditor, formatPropertyValue, globalFrame,
  graphVisibleProperties, handleClearProperty, handleRowAutoKeyToggle,
  handleRowNavigate, handleRowToggleKeyframe, handleRowValueChange,
  handleRowValueCommit, handleValueScrubEnd, handleValueScrubCancel,
  handleValueScrubMove, handleValueScrubStart, isPropertyLocked,
  isCurrentFrameBlocked, onAddKeyframe, onNavigateToKeyframe,
  onCurveVisibilityChange, onDragCancel, onDragEnd,
  onDragStart, onPropertyValueCommit, onPropertyValuePreview,
  resolvedPropertyLinks, resolvedPropertyLinkSourceLabels, removePropertyLink,
  propertyExpressions, propertyLabels, preExpressionPropertyValues,
  resolveExpressionReference, onSetPropertyExpression, openPropertyExpressionEditor,
  onResetPropertiesToDefault, propertyValues, presentation,
  selectedProperty, selectedCurveVisibleExternally, setAllRowsLocked,
  setEditingValueProperty, setValueDrafts, showGraphPane,
  showSinglePropertyCurve, singleCurveMode, skipNextBlurCommitPropertyRef,
  spacious, t, togglePropertyCurve,
  toggleLockedProperty, valueDraftAtFocusRef, valueDrafts,
  expandedGroups, dimensionSeparationByProperty, setAllGroupsExpanded,
  setGroupLocked, toggleGroup, toggleGroupCurves,
  handleClearGroup,
  } = options
  const rowContentProps = useMemo<Omit<DopesheetPropertyRowContentProps, 'row' | 'options'>>(
    () => ({
      activateProperty,
      axisConstraintByProperty,
      autoKeyEnabledByProperty,
      beginPropertyLink,
      canClearRow,
      compoundPropertyRows,
      compoundSecondaryProperties,
      itemId,
      itemFrom,
      currentFrame,
      fps,
      disabled,
      expressionEditor,
      formatPropertyValue,
      globalFrame,
      graphVisibleProperties,
      handleClearProperty,
      handleRowAutoKeyToggle,
      handleRowNavigate,
      handleRowToggleKeyframe,
      handleRowValueChange,
      handleRowValueCommit,
      handleValueScrubEnd,
      handleValueScrubCancel,
      handleValueScrubMove,
      handleValueScrubStart,
      isPropertyLocked,
      isCurrentFrameBlocked,
      onAddKeyframe,
      onNavigateToKeyframe,
      onCurveVisibilityChange,
      onDragCancel,
      onDragEnd,
      onDragStart,
      onPropertyValueCommit,
      onPropertyValuePreview,
      resolvedPropertyLinks,
      resolvedPropertyLinkSourceLabels,
      removePropertyLink,
      propertyExpressions,
      propertyLabels,
      preExpressionPropertyValues,
      resolveExpressionReference,
      onSetPropertyExpression,
      openPropertyExpressionEditor,
      onResetPropertiesToDefault,
      propertyValues,
      presentation,
      selectedProperty,
      selectedCurveVisibleExternally,
      setAllRowsLocked,
      setEditingValueProperty,
      setValueDrafts,
      showGraphPane,
      showSinglePropertyCurve,
      singleCurveMode,
      skipNextBlurCommitPropertyRef,
      spacious,
      t,
      togglePropertyCurve,
      toggleLockedProperty,
      valueDraftAtFocusRef,
      valueDrafts,
    }),
    [
      activateProperty,
      axisConstraintByProperty,
      autoKeyEnabledByProperty,
      beginPropertyLink,
      canClearRow,
      compoundPropertyRows,
      compoundSecondaryProperties,
      itemId,
      itemFrom,
      currentFrame,
      fps,
      disabled,
      expressionEditor,
      formatPropertyValue,
      globalFrame,
      graphVisibleProperties,
      handleClearProperty,
      handleRowAutoKeyToggle,
      handleRowNavigate,
      handleRowToggleKeyframe,
      handleRowValueChange,
      handleRowValueCommit,
      handleValueScrubEnd,
      handleValueScrubCancel,
      handleValueScrubMove,
      handleValueScrubStart,
      isPropertyLocked,
      isCurrentFrameBlocked,
      onAddKeyframe,
      onNavigateToKeyframe,
      onCurveVisibilityChange,
      onDragCancel,
      onDragEnd,
      onDragStart,
      onPropertyValueCommit,
      onPropertyValuePreview,
      resolvedPropertyLinks,
      resolvedPropertyLinkSourceLabels,
      removePropertyLink,
      propertyExpressions,
      propertyLabels,
      preExpressionPropertyValues,
      resolveExpressionReference,
      onSetPropertyExpression,
      openPropertyExpressionEditor,
      onResetPropertiesToDefault,
      propertyValues,
      presentation,
      selectedProperty,
      selectedCurveVisibleExternally,
      setAllRowsLocked,
      setEditingValueProperty,
      setValueDrafts,
      showGraphPane,
      showSinglePropertyCurve,
      singleCurveMode,
      skipNextBlurCommitPropertyRef,
      spacious,
      t,
      togglePropertyCurve,
      toggleLockedProperty,
      valueDraftAtFocusRef,
      valueDrafts,
    ],
  )
  const groupHeaderProps = useMemo<Omit<DopesheetGroupHeaderProps, 'group'>>(
    () => ({
      t,
      expandedGroups,
      graphVisibleProperties,
      dimensionSeparationByProperty,
      canClearRow,
      disabled,
      isPropertyLocked,
      onNavigateToKeyframe,
      onResetPropertiesToDefault,
      presentation,
      setAllGroupsExpanded,
      setAllRowsLocked,
      setGroupLocked,
      toggleGroup,
      toggleGroupCurves,
      handleClearGroup,
      handleRowNavigate,
    }),
    [
      canClearRow,
      dimensionSeparationByProperty,
      disabled,
      expandedGroups,
      graphVisibleProperties,
      handleClearGroup,
      handleRowNavigate,
      isPropertyLocked,
      onNavigateToKeyframe,
      onResetPropertiesToDefault,
      presentation,
      setAllGroupsExpanded,
      setAllRowsLocked,
      setGroupLocked,
      t,
      toggleGroup,
      toggleGroupCurves,
    ],
  )
  return { rowContentProps, groupHeaderProps }
}
